### ISSUE TITLE
explicit parallelism keywords

### ISSUE THREAD

**Issue by twicki** [MeteoSwiss-APN/gtclang#11]
After the discussion with Oli, we concluded that a statement that allows to explicitly disallow parallelism in the ij plane would be interesting as the user might write 
`u[i+1] += u[i]`
and want a reduction but would (due to field versioning) only get a pair-wise addition.
To avoid confusion, one might implement a 
`#pragma noparallel {i,j,k}`
and save this information as an additional field in the SIR.
A final decision on what exactly to do has not been made yet.

**Comment by thfabian** [comment]
While I agree we should extent the SIR to support more general patterns, like reductions, I would propose the following to prevent disambiguity in gtclang. 

If you write
```
u[i+1] += u[i]
```
you get exactly what you have written (possibly even an error message that this is illegal for IJ parallel programs). If you want a reduction, we should expose a function **reduce** or something like this which does this for you.

I addition, I would change the way we handle versioning at the moment at make it *explicit*. Hence, if you want versionning in the following statement:
```
u = u[i] + u[i+1]
u = u[i+1]
```
meaning you meant:
```
u_1 = u[i] + u[i+1]
u_2 = u_1[i+1]
```
You have to explicitly request the *update*
```
u << u[i] + u[i+1]
u << u[i+1]
```
This would solve the disambiguity problem of your example in the sense that we can diagnose it and emit and error message and still gives the ability to have automatic field versioning. Thoughts?

**Comment by twicki** [comment]
I think the feature of allowing exactly this behavior is quite key to have code that is easy to understand and to write.
The fact that GTClang supports 
`u = f(u)`
with versioning lets the user have to worry about one less thing. If they explicitly look for something else than what we currently support, I think one can offer a solution. I don't think making the current state more complex to make a corner-case easier should be the way to go. This is why I am not sure that the `<<` operator would be the best option here. It leaves a lot more room for errors as forgetting it once seems way more likely since I assume there are more use-cases for verisoning than for these reducitons.

I also think that if we allow for the specification of where we allow what kind of parallelism, we should be as flexible as possible.
Assume one would write 
`u[i,j] += u[i+1,j+1]`
and would mean a reduction along i and a simple pair-wise addition in j
```
u[i] += u[i+1]
u_1[j] += u[j+1]
u = u_1
```
there is no elegant way to do it with a new operator. I know that this is quite an unusual example but it would be one where 
`#pragma serial i`
would prove valuable.

Also I think having a more explicit way of defining where parallelism should be applied could prove useful if we want to potentially add something like openMP support for the naive code. 

But I think we should address the two questions separately:

- How do we implement a way of setting those values in GTClang?
- What do we want to store in the SIR and where?

The first question is what this Issue is about.
For the second question I think we should either add a boolean to each statement that is true for ij-parallelism or we have bits for determining parallelism in either dimension. This is also a question on what dawn should support

**Comment by thfabian** [comment]
> This is why I am not sure that the << operator would be the best option here. It leaves a lot more room for errors as forgetting it once seems way more likely since I assume there are more use-cases for verisoning than for these reducitons.

If you forget it you will get an error message as the DAG most likely isn't acyclic anymore. I think it actually would be a good thing if you have to apply the versioning manually because it indicates the point of support of a field has changed and reading a code like this
```
u << f(u)
```
one notices that something unusual (the versioning) is happening! The problem is that with versioning we *change* the semantic of `=`.

> I also think that if we allow for the specification of where we allow what kind of parallelism, we should be as flexible as possible.

Do we want to do this though? Because my understanding is that stencils are usually parallel in the IJ direction and potentially sequential in K. Given that we design a **domain** specific language for stencils  I wouldn't bother with these exotic cases (e.g serial loop in i) and if absolutely required provide a builtin way of doing it (for example define a function which does the reduction `reduction foo { ... }` which can than be applied -- similar to how boundary conditions are handled). Note also that if you want these exotic loops you can always fall back to plain C++ and write your loops manually. We actually once discussed introducing a keyword to escape the DSL inside a Do-Method.

In my opinion, pragmas are a hacky way in C/C++ to make the language express something that it was not designed for. Given our freedom to designing the language, I would opt for more elegant solution by introducing no keywords or something like this. I'm also not sure if we actually want the user to allow where parallelism should be applied.

**Comment by twicki** [comment]
This discussion has been elevated to have an explicit concept for solvers in the vertical and want to have that the syntax here is explicitly parallel - I'll link back to this
